pipeline { agent any

tools {
    maven 'Maven3'
    jdk 'JDK'
}

stages {

    stage('Checkout') {
        steps {
            git branch: 'main',
                url: 'https://github.com/umeshnet2002/Second'
        }
    }

    stage('Build') {
        steps {
            dir('New_test') {
                bat 'mvn clean'
            }
        }
    }

    stage('Compile') {
        steps {
            dir('New_test') {
                bat 'mvn compile'
            }
        }
    }

    stage('Test') {
        steps {
            dir('New_test') {
                bat 'mvn test'
            }
        }

        post {
            always {
                junit '**/target/surefire-reports/*.xml'
            }
        }
    }

    stage('Package') {
        steps {
            dir('New_test') {
                bat 'mvn package'
            }
        }
    }

    stage('Docker Build') {
        steps {
            dir('New_test') {
                bat 'docker build -t testng-framework .'
            }
        }
    }

    stage('Docker Run') {
        steps {
            dir('New_test') {
                bat 'docker run testng-framework'
            }
        }
    }
}

post {
    success {
        echo 'Build Successful'
    }

    failure {
        echo 'Build Failed'
    }
}
}